### ISSUE TITLE
Half opacity flash instead of anti flash

### ISSUE THREAD

**Issue by ujicos** [JulianOzelRose/CSS-MultiHack-Internal#1]
Hey, tried to adjust the 0.0 to e.g 60.0f, this made me flashed forever despite adjusting the parameter that isnt duration. Changing flash to e.g 5 or 10 still makes it invisible, any help??

**Comment by JulianOzelRose** [comment]
Hi, so ```m_fFlashMaxAlpha``` is the brightness level of the flashbang effect. If you watch its value in-game while getting flashed, it always starts from 0, then as a flashbang blinds you, it increments up to around 150 or so. As the effect wears off, it decrements back to 0. So if you force it to a non-zero value, you are essentially making the flashbang's blinding effect permanent. I hope that helps.

**Comment by ujicos** [comment]
So is there no way i could make the flash 50% bright at max?

**Comment by JulianOzelRose** [comment]
I tried this to see if half opacity was possible:

```
if (flashMaxAlpha > 0.0f)
{
	*reinterpret_cast<float*>(localPlayer + offset::m_flFlashMaxAlpha) = flashMaxAlpha / 2.0f;
}
```

It still results in nullified flash effect. To achieve 50% flash alpha, you will probably have to calculate flash alpha dynamically and decrement it. Most implementations of anti-flash I have seen just set alpha to 0 to get rid of it entirely, so it's hard to find much info about reducing opacity. I would say use that code snippet as a starting point.

**Comment by ujicos** [comment]
Thanks for the tip!
I’ll have a look or scrap the idea.

**Comment by JulianOzelRose** [comment]
No problem. Good luck!
